import streamlit.components.v1 as components
import os
from typing import Optional

# Create a custom Streamlit component for PyVis networks with click handling
_component_func = components.declare_component(
    "pyvis_network",
    path=os.path.join(os.path.dirname(__file__), "frontend"),
)

def pyvis_network_component(html_content: str, height: int = 600, key: Optional[str] = None):
    """
    Create a PyVis network component with click event handling.
    
    Parameters:
    -----------
    html_content : str
        The HTML content generated by PyVis
    height : int
        Height of the component in pixels
    key : str, optional
        Unique key for the component
        
    Returns:
    --------
    dict or None
        Dictionary containing clicked node information, or None if no click
    """
    # Call the custom component
    component_value = _component_func(
        html_content=html_content,
        height=height,
        key=key,
        default=None
    )
    
    return component_value